services:
  db:
    image: postgres:14
    container_name: db-odoo
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  odoo:
    image: odoo:17
    container_name: odoo17
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - ./odoo_data:/var/lib/odoo
      - ./addons:/mnt/extra-addons

volumes:
  db_data:
